const Map<String, dynamic> color = {
  'default_white': 0xfff4eeee,
  'default_black': 0xff060606,
  'default_grey': 0xff484f41,
  'default_red': 0xffc9301b,
  'default_blue': 0xff175978,
  'default_yellow': 0xfff0db0f,
  'default_green': 0xff50c918,
  'special_bureautique_1': 0xff263b29,
  'special_bureautique_2': 0xff446c4a,
  'special_bureautique_3': 0xfff5d19d,
  'main_color_1': 0xFF263b29,
  'main_color_2': 0xFFe94e1a,
  'secondary_color_1': 0xFF9eb356,
  'secondary_color_2': 0xFFefb661,
  'secondary_color_2_hover': 0xFFeeb560,
};

const Map<String, dynamic> languagefr = {
  'button_1': {
    'title': 'Gestion',
    'function_1_title': 'Chauffeurs',
    'function_2_title': 'Véhicules',
    'function_3_title': 'Contenants',
    'sub_function_3_title': 'Type Contenants',
    'function_4_title': 'Matières',
  },
  'button_2': {
    'title': 'Partenaires',
    'function_1_title': 'Liste des partenaires',
    'function_2_title': 'Gestion des contacts',
  },
  'button_3': {
    'title': 'Tournées',
    'function_1_title': 'Calendrier hebdomadaire',
    'function_2_title': 'Planification journalière',
    'function_3_title': 'Créer tournée',
    'function_4_title': 'Peser',
  },
  'collecteur_page': {
    'nom_page': 'Chauffeurs',
    'button_1': 'Nouveau Chauffeur',
    'table_title': 'Chauffeurs',
    'column_1_title': 'Nom',
    'column_2_title': 'Sites',
    'icon_button_1_title': 'Modifier Chauffeur',
  },
  'vehicule_page': {
    'nom_page': 'Véhicules',
    'button_1': 'Nouveau Véhicule',
    'table_title': 'Véhicules',
    'column_1_title': 'Nom Véhicules',
    'column_2_title': 'Immatriculation',
    'column_3_title': 'Site',
    'icon_button_1_title': 'Modifier Véhicule'
  },
  'contenant_page': {
    'nom_page': 'Contenants',
    'button_1': 'Nouveau Contenant',
    'table_title': 'Contenants',
    'column_1_title': 'Code-barres',
    'column_2_title': 'Type',
    'column_3_title': 'Actuellement',
    'icon_button_1_title': 'Modifier Contenant'
  },
  'type_contenant_page': {
    'nom_page': 'Types de contenants',
    'button_1': 'Nouveau Type',
    'table_title': 'Types de contenants',
    'column_1_title': 'Désignation',
    'column_2_title': 'Collecte',
    'column_3_title': 'Prépa.',
    'column_4_title': 'Pesée',
    'column_5_title': 'Limit',
    'column_6_title': 'Nombre',
    'icon_button_1_title': 'Modifier Type Contenant'
  },
  'matieres_page': {
    'nom_page': 'Matières collectées',
    'button_1': 'Nouveau matière',
    'table_title': 'Matières collectées',
    'column_1_title': 'Désignation',
    'column_2_title': 'Référence',
    'column_3_title': 'Traitement',
    'icon_button_1_title': 'Modifier Type Contenant',
    'icon_button_2_title': 'Historique des collectes',
  },
  'create_collecteur_page': {
    'nom_page': 'Nouveau chauffeur',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau chauffeur',
    'form_subtitle': 'Informations',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Site*',
    'field_4_title': 'Date de naissance*',
    'field_4_button': 'Choisir la date',
  },
  'modify_collecteur_page': {
    'nom_page': 'Modify chauffeur',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Modify chauffeur',
    'form_subtitle': 'Informations',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Site*',
    'field_4_title': 'Date de naissance*',
    'field_4_button': 'Choisir la date',
  },
  'create_vehicule_page': {
    'nom_page': 'Nouveau véhicule',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau véhicule',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation*',
    'field_2_title': 'Immatriculation',
    'field_3_title': 'Type*',
    'field_4_title': 'Site associé*',
    'field_5_title': 'Position (ordre) *',
    'field_6_title': 'Couleur*',
    'field_6_button': 'Choisir la couleur',
    'field_6_form_title': 'Sélectionnez la couleur',
    'field_6_form_button': 'Choisir',
  },
  'modify_vehicule_page': {
    'nom_page': 'Modifier véhicule',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Modifier véhicule',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation*',
    'field_2_title': 'Immatriculation',
    'field_3_title': 'Type*',
    'field_4_title': 'Site associé*',
    'field_5_title': 'Position (ordre) *',
    'field_6_title': 'Couleur*',
    'field_6_button': 'Choisir la couleur',
    'field_6_form_title': 'Sélectionnez la couleur',
    'field_6_form_button': 'Choisir',
  },
  'create_matieres_page': {
    'nom_page': 'Nouvelle matière',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouvelle matière',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation *',
    'field_2_title': 'Désignation en anglais',
    'field_3_title': 'Matière parente *',
    'field_4_title': 'Référence',
    'field_5_title': 'Couleur*',
    'field_5_button': 'Choisir la couleur',
    'field_5_subtitle': 'Code',
    'field_5_form_title': 'Sélectionnez la couleur',
    'field_5_form_button': 'Choisir',
    'field_6_title': 'Actif*',
    'field_6_choice_1': 'Actif',
    'field_6_choice_2': 'Pas Actif',
  },
  'modify_matieres_page': {
    'nom_page': 'Modifier matière',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Modifier matière',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation *',
    'field_2_title': 'Désignation en anglais',
    'field_3_title': 'Matière parente *',
    'field_4_title': 'Référence',
    'field_5_title': 'Couleur*',
    'field_5_button': 'Choisir la couleur',
    'field_5_subtitle': 'Code',
    'field_5_form_title': 'Sélectionnez la couleur',
    'field_5_form_button': 'Choisir',
    'field_6_title': 'Actif*',
    'field_6_choice_1': 'Actif',
    'field_6_choice_2': 'Pas Actif',
  },
  'create_contenant_page': {
    'nom_page': 'Nouveau contenant',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau contenant',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Code-barres*',
    'field_2_title': 'Type*',
    'field_3_title': 'Actuellement*',
    'field_3_choice_1': 'Disponible',
    'field_3_choice_2': 'PasDisponible',
  },
  'create_type_contenant_page': {
    'nom_page': 'Nouveau type de contenants',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau type de contenants',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation *',
    'field_2_title': 'Poids*',
    'field_3_title': 'Poids limite*',
    'field_4_title': 'Noter',
    'field_5_title': 'Collecté',
    'field_6_title': 'Préparé',
    'field_7_title': 'Pesée',
  },
  'partenaire_page': {
    'nom_page': 'Partenaires',
    'button_1': 'Nouveau Partenaire',
    'table_title': 'Liste des partenaires',
    'column_2_title': 'Actif',
    'column_3_title': 'Désignation',
    'column_4_title': 'Contact',
    'icon_button_1_title_1': 'Ajouter le contact',
    'icon_button_1_title_2': 'Afficher le contact principal'
  },
  'create_partenaire_page': {
    'nom_page': 'Nouveau partenaire',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': ' Nouveau partenaire',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom*',
    'field_2_title': 'Siret',
    'field_3_title': 'Type',
    'field_4_title': 'Actif*',
    'field_4_choice_1': 'Actif',
    'field_4_choice_2': 'Pas Actif',
    'field_5_title': 'Noter',
  },
  'add_contact_partenaire_page': {
    'nom_page': 'Nouveau contact',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau contact',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Telephone 1',
    'field_4_title': 'Telephone 2',
    'field_5_title': 'Email',
    'field_6_title': 'Mot de passe',
    'field_7_title': 'Note/Remarque',
    'field_8_title': 'Reçoit les factures',
    'field_9_title': 'Reçoit les rapports',
    'field_10_title': 'Accès à extranet',
  },
  'view_contact_partenaire_page': {
    'nom_page': 'Contact principal',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Voir contact',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Telephone 1',
    'field_4_title': 'Telephone 2',
    'field_5_title': 'Email',
    'field_6_title': 'Mot de passe',
    'field_7_title': 'Note/Remarque',
    'field_8_title': 'Reçoit les factures',
    'field_9_title': 'Reçoit les rapports',
    'field_10_title': 'Accès à extranet',
  },
  'contact_page': {
    'nom_page': 'Gestion des contacts',
    'button_1': 'Nouveau Contact',
    'table_title': 'Contacts',
    'column_1_title': 'Prénom et nom',
    'column_2_title': 'Email',
    'column_3_title': 'Télephone(s)',
    'column_4_title': 'Partenaire(s)',
    'icon_button_1_title': 'Éditer partenaire',
    'edit_partenaire_form': {
      'button_1': 'Annuler',
      'form_title': 'Éditer Partenaire',
      'icon_button_1': 'Ajouter Partenaire',
      'icon_button_2': 'Dissocier le partenaire de ce contact',
    },
  },
  'warning': {
    'not_null': 'Cela ne peut pas être nul',
  },
};
