const Map<String, dynamic> color = {
  'default_white': 0xfff4eeee,
  'default_black': 0xff060606,
  'default_grey': 0xff484f41,
  'default_red': 0xffc9301b,
  'default_blue': 0xff175978,
  'default_yellow': 0xfff0db0f,
  'special_bureautique_1': 0xff263b29,
  'special_bureautique_2': 0xff446c4a,
  'special_bureautique_3': 0xfff5d19d,
  'main_color_1': 0xFF263b29,
  'main_color_2': 0xFFe94e1a,
  'secondary_color_1': 0xFF9eb356,
  'secondary_color_2': 0xFFefb661,
  'secondary_color_2_hover': 0xFFeeb560,
};

const Map<String, dynamic> languagefr = {
  'button_1': {
    'title': 'Gestion',
    'function_1_title': 'Chauffeurs',
    'function_2_title': 'Véhicules',
    'function_3_title': 'Contenants',
    'sub_function_3_title': 'Type Contenants',
    'function_4_title': 'Matières',
  },
  'button_2': {
    'title': 'Partenaires',
    'function_1_title': 'Liste des partenaires',
    'function_2_title': 'Gestion des contacts',
  },
  'button_3': {
    'title': 'Tournées',
    'function_1_title': 'Calendrier hebdomadaire',
    'function_2_title': 'Planification journalière',
    'function_3_title': 'Créer tournée',
    'function_4_title': 'Peser',
  },
  'collecteur_page': {
    'nom_page': 'Chauffeurs',
    'button_1': 'Nouveau Chauffeur',
    'table_title': 'Chauffeurs',
    'column_1_title': 'Nom',
    'column_2_title': 'Sites'
  },
  'vehicule_page': {
    'nom_page': 'Véhicules',
    'button_1': 'Nouveau Véhicule',
    'table_title': 'Véhicules',
    'column_1_title': 'Nom Véhicules',
    'column_2_title': 'Immatriculation',
    'column_3_title': 'Site',
  },
  'contenant_page': {
    'nom_page': 'Contenants',
    'button_1': 'Nouveau Contenant',
    'table_title': 'Contenants',
    'column_1_title': 'Code-barres',
    'column_2_title': 'Type',
    'column_3_title': 'Actuellement',
  },
  'type_contenant_page': {
    'nom_page': 'Types de contenants',
    'button_1': 'Nouveau Type',
    'table_title': 'Types de contenants',
    'column_1_title': 'Désignation',
    'column_2_title': 'Collecte',
    'column_3_title': 'Prépa.',
    'column_4_title': 'Pesée',
    'column_5_title': 'Limit',
    'column_6_title': 'Nombre',
  },
};
