import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

const Map<String, dynamic> color = {
  'default_white': 0xfff4eeee,
  'default_black': 0xff060606,
  'default_grey': 0xff484f41,
  'default_red': 0xffc9301b,
  'default_blue': 0xff175978,
  'default_yellow': 0xfff0db0f,
  'default_green': 0xff50c918,
  'special_bureautique_1': 0xff263b29,
  'special_bureautique_2': 0xff446c4a,
  'special_bureautique_3': 0xfff5d19d,
  'main_color_1': 0xFF263b29,
  'main_color_2': 0xFFe94e1a,
  'secondary_color_1': 0xFF9eb356,
  'secondary_color_2': 0xFFefb661,
  'secondary_color_2_hover': 0xFFeeb560,
};

const Map<String, dynamic> languagefr = {
  'button_1': {
    'title': 'Gestion',
    'function_1_title': 'Chauffeurs',
    'function_2_title': 'Véhicules',
    'function_3_title': 'Contenants',
    'sub_function_3_title': 'Type Contenants',
    'function_4_title': 'Matières',
  },
  'button_2': {
    'title': 'Partenaires',
    'function_1_title': 'Liste des partenaires',
    'sub_function_1_title': 'Type Partenaires',
    'function_2_title': 'Gestion des contacts',
  },
  'button_3': {
    'title': 'Tournées',
    'function_1_title': 'Calendrier hebdomadaire',
    'function_2_title': 'Planification journalière',
    'function_3_title': 'Créer tournée',
    'function_4_title': 'Peser',
  },
  'header_page': {
    'user_infor_form': {
      'button_1': 'Informations utilisateur',
      'button_2': 'Se déconnecter',
    },
  },
  'user_infor_page': {
    'nom_page': 'Informations utilisateur',
    'change_user_name_form': {
      'form_title': 'Changer le nom utilisateur',
      'button_1': 'Changer',
      'field_1_title': 'Nom utilisateur',
    },
    'change_password_form': {
      'form_title': 'Changer le mot de passe',
      'button_1': 'Changer',
      'field_1_title': 'Mot de passe actuel',
      'field_2_title': 'Nouveau mot de passe',
      'field_3_title': 'Confirmez le mot de passe',
    },
  },
  'collecteur_page': {
    'nom_page': 'Chauffeurs',
    'button_1': 'Nouveau Chauffeur',
    'table_title': 'Chauffeurs',
    'column_1_title': 'Nom',
    'column_2_title': 'Sites',
    'icon_button_1_title': 'Modifier Chauffeur',
  },
  'vehicule_page': {
    'nom_page': 'Véhicules',
    'button_1': 'Nouveau Véhicule',
    'table_title': 'Véhicules',
    'column_1_title': 'Nom Véhicules',
    'column_2_title': 'Immatriculation',
    'column_3_title': 'Site',
    'icon_button_1_title': 'Modifier Véhicule'
  },
  'contenant_page': {
    'nom_page': 'Contenants',
    'button_1': 'Nouveau Contenant',
    'table_title': 'Contenants',
    'column_1_title': 'Code-barres',
    'column_2_title': 'Type',
    'column_3_title': 'Actuellement',
    'icon_button_1_title': 'Modifier Contenant'
  },
  'type_contenant_page': {
    'nom_page': 'Types de contenants',
    'button_1': 'Nouveau Type',
    'table_title': 'Types de contenants',
    'column_1_title': 'Désignation',
    'column_2_title': 'Collecte',
    'column_3_title': 'Prépa.',
    'column_4_title': 'Pesée',
    'column_5_title': 'Limit',
    'column_6_title': 'Nombre',
    'icon_button_1_title': 'Modifier Type Contenant'
  },
  'matieres_page': {
    'nom_page': 'Matières collectées',
    'button_1': 'Nouveau matière',
    'table_title': 'Matières collectées',
    'column_1_title': 'Désignation',
    'column_2_title': 'Référence',
    'column_3_title': 'Traitement',
    'icon_button_1_title': 'Modifier Type Contenant',
    'icon_button_2_title': 'Historique des collectes',
  },
  'create_collecteur_page': {
    'nom_page': 'Nouveau chauffeur',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau chauffeur',
    'form_subtitle': 'Informations',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Site*',
    'field_4_title': 'Date de naissance*',
    'field_4_button': 'Choisir la date',
  },
  'modify_collecteur_page': {
    'nom_page': 'Modify chauffeur',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Modify chauffeur',
    'form_subtitle': 'Informations',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Site*',
    'field_4_title': 'Date de naissance*',
    'field_4_button': 'Choisir la date',
  },
  'create_vehicule_page': {
    'nom_page': 'Nouveau véhicule',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau véhicule',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation*',
    'field_2_title': 'Immatriculation',
    'field_3_title': 'Type*',
    'field_4_title': 'Site associé*',
    'field_5_title': 'Position (ordre) *',
    'field_6_title': 'Couleur*',
    'field_6_button': 'Choisir la couleur',
    'field_6_form_title': 'Sélectionnez la couleur',
    'field_6_form_button': 'Choisir',
  },
  'modify_vehicule_page': {
    'nom_page': 'Modifier véhicule',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Modifier véhicule',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation*',
    'field_2_title': 'Immatriculation',
    'field_3_title': 'Type*',
    'field_4_title': 'Site associé*',
    'field_5_title': 'Position (ordre) *',
    'field_6_title': 'Couleur*',
    'field_6_button': 'Choisir la couleur',
    'field_6_form_title': 'Sélectionnez la couleur',
    'field_6_form_button': 'Choisir',
  },
  'create_matieres_page': {
    'nom_page': 'Nouvelle matière',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouvelle matière',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation *',
    'field_2_title': 'Désignation en anglais',
    'field_3_title': 'Matière parente *',
    'field_4_title': 'Référence',
    'field_5_title': 'Couleur*',
    'field_5_button': 'Choisir la couleur',
    'field_5_subtitle': 'Code',
    'field_5_form_title': 'Sélectionnez la couleur',
    'field_5_form_button': 'Choisir',
    'field_6_title': 'Actif*',
    'field_6_choice_1': 'Actif',
    'field_6_choice_2': 'Pas Actif',
  },
  'modify_matieres_page': {
    'nom_page': 'Modifier matière',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Modifier matière',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation *',
    'field_2_title': 'Désignation en anglais',
    'field_3_title': 'Matière parente *',
    'field_4_title': 'Référence',
    'field_5_title': 'Couleur*',
    'field_5_button': 'Choisir la couleur',
    'field_5_subtitle': 'Code',
    'field_5_form_title': 'Sélectionnez la couleur',
    'field_5_form_button': 'Choisir',
    'field_6_title': 'Actif*',
    'field_6_choice_1': 'Actif',
    'field_6_choice_2': 'Pas Actif',
  },
  'create_contenant_page': {
    'nom_page': 'Nouveau contenant',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau contenant',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Code-barres*',
    'field_2_title': 'Type*',
    'field_3_title': 'Actuellement*',
    'field_3_choice_1': 'Disponible',
    'field_3_choice_2': 'PasDisponible',
  },
  'create_type_contenant_page': {
    'nom_page': 'Nouveau type de contenants',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau type de contenants',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation *',
    'field_2_title': 'Poids*',
    'field_3_title': 'Poids limite*',
    'field_4_title': 'Noter',
    'field_5_title': 'Collecté',
    'field_6_title': 'Préparé',
    'field_7_title': 'Pesée',
  },
  'partenaire_page': {
    'nom_page': 'Partenaires',
    'button_1': 'Nouveau Partenaire',
    'table_title': 'Liste des partenaires',
    'column_2_title': 'Actif',
    'column_3_title': 'Désignation',
    'column_4_title': 'Contact',
    'icon_button_1_title_1': 'Ajouter le contact',
    'icon_button_1_title_2': 'Afficher le contact principal'
  },
  'type_partenaire_page': {
    'nom_page': 'Types de partenaires',
    'button_1': 'Nouveau Type',
    'table_title': 'Types de partenaires',
    'column_1_title': 'Désignation',
    'column_2_title': 'Nombre',
    'icon_button_1_title': 'Modifier Type Partenaires'
  },
  'create_type_partenaire_page': {
    'nom_page': 'Nouveau type de partenaires',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau type de partenaires',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Désignation *',
    'field_2_title': 'Poids*',
    'field_3_title': 'Poids limite*',
    'field_4_title': 'Noter',
    'field_5_title': 'Collecté',
    'field_6_title': 'Préparé',
    'field_7_title': 'Pesée',
  },
  'create_partenaire_page': {
    'nom_page': 'Nouveau partenaire',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': ' Nouveau partenaire',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom*',
    'field_2_title': 'Siret',
    'field_3_title': 'Type',
    'field_4_title': 'Actif*',
    'field_4_choice_1': 'Actif',
    'field_4_choice_2': 'Pas Actif',
    'field_5_title': 'Noter',
  },
  'add_contact_partenaire_page': {
    'nom_page': 'Nouveau contact',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau contact',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Telephone 1',
    'field_4_title': 'Telephone 2',
    'field_5_title': 'Email',
    'field_6_title': 'Mot de passe',
    'field_7_title': 'Note/Remarque',
    'field_8_title': 'Reçoit les factures',
    'field_9_title': 'Reçoit les rapports',
    'field_10_title': 'Accès à extranet',
  },
  'view_contact_partenaire_page': {
    'nom_page': 'Contact principal',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Voir contact',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Telephone 1',
    'field_4_title': 'Telephone 2',
    'field_5_title': 'Email',
    'field_6_title': 'Mot de passe',
    'field_7_title': 'Note/Remarque',
    'field_8_title': 'Reçoit les factures',
    'field_9_title': 'Reçoit les rapports',
    'field_10_title': 'Accès à extranet',
  },
  'contact_page': {
    'nom_page': 'Gestion des contacts',
    'button_1': 'Nouveau Contact',
    'table_title': 'Contacts',
    'column_1_title': 'Prénom et nom',
    'column_2_title': 'Email',
    'column_3_title': 'Télephone(s)',
    'column_4_title': 'Partenaire(s)',
    'icon_button_1_title': 'Éditer partenaire',
    'edit_partenaire_form': {
      'button_1': 'Annuler',
      'form_title': 'Éditer Partenaire',
      'icon_button_1': 'Ajouter Partenaire',
      'icon_button_2': 'Dissocier le partenaire de ce contact',
    },
  },
  'view_contact_page': {
    'nom_page': 'Contact',
    'contact_form': {
      'nom_form': 'Contact',
      'button_1': 'Enregistrer',
      'button_2': 'Annuler',
      'form_subtitle': 'Informations et paramètres',
      'field_1_title': 'Nom*',
      'field_2_title': 'Prenom*',
      'field_3_title': 'Telephone 1',
      'field_4_title': 'Telephone 2',
      'field_5_title': 'Email',
      'field_6_title': 'Mot de passe',
      'field_7_title': 'Note/Remarque',
      // 'field_8_title': 'Reçoit les factures',
      // 'field_9_title': 'Reçoit les rapports',
      // 'field_10_title': 'Accès à extranet',
    },
    'partenaire_form': {
      'nom_form': 'Liste des partenaires',
    },
  },
  'create_contact_page': {
    'nom_page': 'Nouveau contact',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau contact',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom*',
    'field_2_title': 'Prenom*',
    'field_3_title': 'Telephone 1',
    'field_4_title': 'Telephone 2',
    'field_5_title': 'Email',
    'field_6_title': 'Mot de passe',
    'field_7_title': 'Note/Remarque',
    'field_8_title': 'Reçoit les factures',
    'field_9_title': 'Reçoit les rapports',
    'field_10_title': 'Accès à extranet',
    'field_11_title': 'Partenaire',
  },
  'view_partenaire_page': {
    'nom_page': 'Voir Partenaire',
    'partenaire_form': {
      'nom_form': 'Partenaire',
      'button_1': 'Enregistrer',
      'form_subtitle': 'Informations et paramètres',
      'field_1_title': 'Nom',
      'field_2_title': 'Siret',
      'field_3_title': 'Type',
      'field_4_title': 'Actif*',
      'field_4_choice_1': 'Actif',
      'field_4_choice_2': 'Pas Actif',
      'field_5_title': 'Noter',
    },
    'contact_form': {
      'nom_form': 'Contact',
      'column_1_title': 'Contact',
      'column_2_title': 'Principal',
      'column_3_title': 'Rapports',
      'column_4_title': 'Factures',
      'column_5_title': 'Accès',
      'hint_text_1': 'Modifier',
      'hint_text_2': 'Dissocier',
    },
    'adresse_form': {
      'nom_form': 'Adresses',
      'button_1': 'Nouvelle adresse',
      'sub_form_button_1': 'Modifier Adresse'
    },
    'frequence_form': {
      'nom_form': 'Fréquences de passage',
      'button_1': 'Nouvelle fréquence',
      'sub_form_button_1': 'Modifier fréquence'
    },
    'contenant_form': {
      'nom_form': 'Contenants et matières',
      'button_1': 'Nouveau contenant',
      'sub_form_title': 'Modifier fréquence',
      'sub_column_1_title': 'A collecter',
      'sub_column_2_title': 'Modifier fréquence'
    },
  },
  'create_adresse_page': {
    'nom_page': 'Nouvelle adresse',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Nouveau adresse',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Nom Adresse*',
    'field_2_title': 'Adresse 1*',
    'field_3_title': 'Adresse 2',
    'field_4_title': 'Code Postal*',
    'field_5_title': 'Ville',
    'field_6_title': 'Pays',
    'field_7_title': 'Position',
    'field_7_hint': 'Recherche par Google Map',
    'field_8_title': 'Latitude',
    'field_9_title': 'Longitude',
    'field_10_title': 'Étage',
    'field_11_title': 'Ascenseur',
    'field_12_title': 'Passages',
    'field_13_title': 'Facturation',
    'field_14_title': 'Note/Accès',
    'field_15_title': 'Prix du passage',
    'field_16_title': 'Temps sur place',
    'field_17_title': 'Surface plancher',
    'position_form': {
      'form_nom': 'Position',
      'button_1': 'Sélectionner',
      'hint_1': 'Chercher',
    }
  },
  'create_adresse_full_page': {
    'nom_page': 'Nouvelle adresse',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'adresse_form': {
      'form_title': 'Nouveau adresse',
      'form_subtitle': 'Informations et paramètres',
      'field_1_title': 'Nom Adresse*',
      'field_2_title': 'Adresse 1*',
      'field_3_title': 'Adresse 2',
      'field_4_title': 'Code Postal*',
      'field_5_title': 'Ville',
      'field_6_title': 'Pays',
      'field_7_title': 'Position',
      'field_7_hint': 'Recherche par Google Map',
      'field_8_title': 'Latitude',
      'field_9_title': 'Longitude',
      'field_10_title': 'Étage',
      'field_11_title': 'Ascenseur',
      'field_12_title': 'Passages',
      'field_13_title': 'Facturation',
      'field_14_title': 'Note/Accès',
      'field_15_title': 'Prix du passage',
      'field_16_title': 'Temps sur place',
      'field_17_title': 'Surface plancher',
    },
    'position_form': {
      'form_nom': 'Position',
      'button_1': 'Sélectionner',
      'hint_1': 'Chercher',
    },
    'horaires_form': {
      'form_title': 'Ajouter des Fréquences',
      'form_subtitle': 'Informations sur le horaire',
      'column_1_title': 'Jour',
      'column_2_title': 'Heure de début',
      'column_3_title': 'Heure de fin',
      'column_4_title': 'Date de début',
      'column_5_title': 'Date de fin',
      'column_6_title': 'Frequence(Toutes les X semaines)',
      'column_7_title': 'Tarif',
      'column_8_title': 'Véhicule',
      'column_9_button_1': 'Confirmer',
      'column_9_button_2': 'Annuler',
    },
    'contenant_form': {
      'form_title': 'Ajouter des Contenants',
      'form_subtitle': 'Conteneurs disponibles',
    },
    'confirm_form': {
      'button_1': 'Enregistrer',
      'button_2': 'Annuler',
    },
    'confirm_dialog': {
      'dialog_title': 'Annuler Création Adresse',
      'question': 'Terminer la création de cette adresse?',
      'line_1': 'Nombre de contenants que vous avez ajoutés:',
      'line_2': 'Nombre de fréquences que vous avez ajoutées:',
      'button_1': 'Oui',
      'button_2': 'Non',
    },
    'cancel_dialog': {
      'dialog_title': 'Annuler Création Adresse',
      'question': 'Annuler la création de cette adresse?',
      'button_1': 'Oui',
      'button_2': 'Non',
    },
  },
  'modify_addresse_partenaire_page': {
    'nom_page': 'Informations adresse',
    'subtitle_page': 'Modifier adresse du partenaire',
    'adresse_form': {
      'button_nom': 'Localisation',
      'button_1': 'Enregistrer',
      'button_2': 'Annuler',
      'form_subtitle': 'Informations sur adresse',
      'field_1_title': 'Nom Adresse*',
      'field_2_title': 'Adresse 1*',
      'field_3_title': 'Adresse 2',
      'field_4_title': 'Code Postal*',
      'field_5_title': 'Ville',
      'field_6_title': 'Pays',
      'field_7_title': 'Latitude',
      'field_8_title': 'Longitude',
      'field_9_title': 'Étage',
      'field_10_title': 'Note/Accès',
      'field_11_title': 'Ascenseur',
      'field_12_title': 'Passages',
      'field_13_title': 'Facturation',
      'field_14_title': 'Prix du passage',
      'field_15_title': 'Temps sur place',
      'field_16_title': 'Surface plancher',
    },
    'horaires_form': {
      'button_nom': 'Horaires',
      'button_1': 'Enregistrer',
      'button_2': 'Annuler',
      'form_subtitle': 'Informations sur le horaire',
      'field_1_title': 'Heure de début',
      'field_2_title': 'Heure de fin',
      'field_3_title': 'Date de début',
      'field_4_title': 'Date de fin',
      'field_5_title': 'Frequence*(Toutes les X semaines) : ',
      'field_6_title': 'Tarif',
      'field_7_title': 'Jour',
      'field_8_title': 'Véhicule',
    },
    'contact_form': {
      'button_nom': 'Contacts',
      'button_1': 'Annuler',
      'form_subtitle': 'Informations des contacts',
      'hint_1_title': 'Dissocier le contact',
      'hint_2_title': 'Ajouter le contact',
    }
  },
  'modify_addresse_multiple_page': {
    'nom_page': 'Informations adresse',
    'subtitle_page': 'Modifier adresse du partenaire',
    'adresse_form': {
      'button_nom': 'Localisation',
      'button_1': 'Enregistrer',
      'button_2': 'Annuler',
      'form_subtitle': 'Informations sur adresse',
      'field_1_title': 'Nom Adresse*',
      'field_2_title': 'Adresse 1*',
      'field_3_title': 'Adresse 2',
      'field_4_title': 'Code Postal*',
      'field_5_title': 'Ville',
      'field_6_title': 'Pays',
      'field_7_title': 'Latitude',
      'field_8_title': 'Longitude',
      'field_9_title': 'Étage',
      'field_10_title': 'Note/Accès',
      'field_11_title': 'Ascenseur',
      'field_12_title': 'Passages',
      'field_13_title': 'Facturation',
      'field_14_title': 'Prix du passage',
      'field_15_title': 'Temps sur place',
      'field_16_title': 'Surface plancher',
    },
    'horaires_form': {
      'button_nom': 'Horaires',
      'button_1': 'Enregistrer',
      'button_2': 'Annuler',
      'form_subtitle': 'Informations sur le horaire',
      'column_1_title': 'Jour',
      'column_2_title': 'Heure de début',
      'column_3_title': 'Heure de fin',
      'column_4_title': 'Date de début',
      'column_5_title': 'Date de fin',
      'column_6_title': 'Frequence(Toutes les X semaines)',
      'column_7_title': 'Tarif',
      'column_8_title': 'Véhicule',
      'column_9_button_1': 'Confirmer',
      'column_9_button_2': 'Annuler',
    },
    'contact_form': {
      'button_nom': 'Contacts',
      'button_1': 'Annuler',
      'form_subtitle': 'Informations des contacts',
      'hint_1_title': 'Dissocier le contact',
      'hint_2_title': 'Ajouter le contact',
    }
  },
  'modify_frequence_partenaire_page': {
    'nom_page': 'Modifier Fréquence',
    'button_1': 'Enregistrer',
    'button_2': 'Annuler',
    'form_title': 'Fréquence',
    'form_subtitle': 'Informations sur le horaire',
    'field_1_title': 'Heure de début',
    'field_2_title': 'Heure de fin',
    'field_3_title': 'Date de début',
    'field_4_title': 'Date de fin',
    'field_5_title': 'Frequence*(Toutes les X semaines) : ',
    'field_6_title': 'Tarif',
    'field_7_title': 'Jour',
    'field_8_title': 'Véhicule',
  },
  'create_tournee_page': {
    'nom_page': 'Créer tournée',
    'button_1': 'Annuler',
    'button_2': 'Ajouter dans duration',
    'button_3': 'Ajouter un tournée',
    'form_title': 'Créer nouveau tournée',
    'form_subtitle': 'Informations et paramètres',
    'field_1_title': 'Chauffeur',
    'field_2_title': 'Véhicule',
    'field_3_title': 'Date de Tournée',
    'field_4_title': 'Heure de début',
    'confirm_button': 'Confirmer',
    'change_button': 'Changer',
    'field_5_title': 'Partenaire',
    'field_6_title': 'Adresse',
    'field_7_title': 'Jour',
    'field_8_title': 'Fréquence',
    'duration_line': 'Duration',
    'step_form': {
      'form_title': 'Liste des étapes',
      'form_subtitle': 'Informations sur les étapes',
      'field_1_title': 'Etape',
      'field_2_title': 'Nom Partenaire',
      'field_3_title': 'Nom Partenaire Adresse',
      'field_4_title': 'Adresse',
      'field_5_title': 'Durée',
      'field_6_title': 'Tarif',
      'add_button': 'Ajouter',
      'remove_button': 'Supprimer',
    },
  },
  'warning': {
    'not_null': 'Cela ne peut pas être nul',
  },
};

const Map<String, IconData> myIconCollection = {
  'favorite': Icons.favorite,
  'home': Icons.home,
  'android': Icons.android,
  'album': Icons.album,
  'ac_unit': Icons.ac_unit,
  'building': FontAwesomeIcons.building,
  'city': FontAwesomeIcons.city,
  'flask': FontAwesomeIcons.flask,
  'flag': FontAwesomeIcons.flag,
  'utensils': FontAwesomeIcons.utensils,
};
